version: '3.8'
services:
  nextjs:
    build: .
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run start"
    env_file:
      - .env.local
